version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-server
    ports:
      - 8001:8080
    networks: 
      easygo:

networks:
  easygo: